# Generated by Django 5.2.1 on 2025-06-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20250615_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='previous_stock',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='new_stock',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='quantity_change',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='notes',
            field=models.TextField(),
        ),
    ]
