# Generated by Django 5.2.1 on 2025-06-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_default_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='setting_type',
            field=models.CharField(choices=[('general', 'General'), ('business', 'Business'), ('notification', 'Notification'), ('payment', 'Payment'), ('appearance', 'Appearance'), ('system', 'System')], max_length=20),
        ),
    ]
